# Generated by Django 4.0 on 2021-12-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='purchase_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='reward_points',
            field=models.IntegerField(),
        ),
    ]
